-- Migration: add school branding columns
-- Run this if you already have the schema set up

ALTER TABLE schools ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7) DEFAULT '#3B82F6';
ALTER TABLE schools ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(7) DEFAULT '#1E40AF';
ALTER TABLE schools ADD COLUMN IF NOT EXISTS tagline VARCHAR(255);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS announcement TEXT;
ALTER TABLE schools ADD COLUMN IF NOT EXISTS announcement_color VARCHAR(7) DEFAULT '#F59E0B';
ALTER TABLE schools ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
